services:
  - type: web
    name: promark-backend
    runtime: python
    repo: https://github.com/YOUR_USERNAME/promark-backend
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PIP_NO_CACHE_DIR
        value: "true"
      - key: BACKEND_ENV
        value: production
    autoDeploy: true
    rootDir: .
